### ISSUE TITLE
cannot call `verificationMethod.getController()` unless `@context` is set

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/did-common-java#23]
running into the following error when calling `verificationMethod.getController()` despite `controller` being present:

```
java.lang.IllegalArgumentException: Cannot get string 'controller' from {type=JsonWebKey2020, id=did:key:zQ3shjmnWpSDEbYKpaFm4kTs9kXyqG6N2QwCYHNPP4yubqgJS#zQ3shjmnWpSDEbYKpaFm4kTs9kXyqG6N2QwCYHNPP4yubqgJS, controller=did:key:zQ3shjmnWpSDEbYKpaFm4kTs9kXyqG6N2QwCYHNPP4yubqgJS, publicKeyJwk={kty=EC, use=sig, crv=secp256k1, kid=vvDdKCl15we8gff3Oei7PbQoAoAAb_b9VVtK9uUDiuU, x=TEIJN9vnTq1EXMkqzo7yN_867-foKc2pREv45Fw_QA8, y=9yiymlzdxKCiRbYq7p-ArRB-C1ytjHE-eb7RDTi6rVc, alg=ES256K}}
	at foundation.identity.jsonld.JsonLDUtils.jsonLdGetString(JsonLDUtils.java:162)
	at foundation.identity.did.VerificationMethod.getController(VerificationMethod.java:140)
	at web5.sdk.dids.DidKeyTest$ResolveTest.resolving a secp256k1 DID works(DidKeyTest.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```

digging into the code a bit. it seems as if `VerificationMethod` requires a JSON-LD `@context` in order to access the `controller` property.

Is this intentional? I don't see `context` being a required property of a verification method in the [DID spec](https://www.w3.org/TR/did-core/#dfn-verificationmethod). 

Maybe i'm understanding incorrectly but, if context is required, i'm not sure how this library is expected to be used to build strongly typed DID documents for did methods that do not require verification methods to include `@context`

**Comment by peacekeeper** [comment]
@mistermoe I think this has been fixed in https://github.com/decentralized-identity/did-common-java/commit/681113fcf58913bd62c2fd62cb0a02b0172b14c1. Could you try again with latest version 0.10.0 ?

**Comment by mistermoe** [comment]
that fixed the issue. Thanks!
